#--------------------------通用配置-------------------------
spring:
  application:
    # 应用名
    name: EggplantNovel
  profiles:
    # 激活特定配置
    active: dev
  jackson:
    generator:
      # JSON 序列化时，将所有 Number 类型的属性都转为 String 类型返回，避免前端数据精度丢失的问题。
      # 由于 Javascript 标准规定所有数字处理都应使用 64 位 IEEE 754 浮点值完成，
      # 结果是某些 64 位整数值无法准确表示（尾数只有 51 位宽）
      write-numbers-as-strings: true
  servlet:
    multipart:
      # 上传文件最大大小
      max-file-size: 5MB
server:
  # 端口号
  port: 8888

--- #---------------------自定义配置----------------------------
novel:
  # 跨域配置
  cors:
    # 允许跨域的域名
    allow-origins:
      - http://localhost:1024
      - http://localhost:8080
  # JWT密钥
  jwt:
    secret: E66559580A1ADF48CDD928516062F12E
  # XSS 过滤配置
  xss:
    # 过滤开关
    enabled: true
    # 排除链接
    excludes:
      - /system/notice/*
  file:
    # 文件上传配置
    upload:
      # 上传路径
      path: /Users/xiongxiaoyang/upload

--- #---------------------数据源配置----------------------------
spring:
  datasource:
    url: jdbc:mysql://106.15.106.128:3306/novel?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: novel
    password: anP8hyPSyppiWrbz

--- #---------------------中间件配置---------------------------
spring:
  # Redis 配置
  redis:
    host: 127.0.0.1
    port: 6379
    # password:

  elasticsearch:
    # 是否开启 elasticsearch 搜索引擎功能：true-开启 false-不开启
    enable: false
